/** @deprecated Import from scheduleAssignees.ts — re-exported for backward compatibility. */
export {
  type CompanyUsersTabRow,
  type ScheduleAssigneeOption,
  type ScheduleAuditorOption,
  type ScheduleAssigneeDiagnostics,
  type ScheduleAuditorDiagnostics,
  normalizeScheduleValue,
  isActiveCompanyUsersTabRow,
  isActiveCompanyUser,
  canCompleteAuditUser,
  isAuditorCompanyUsersTabRow,
  belongsToCompanyUsersTabRow,
  matchesScheduleAreaForUser,
  buildScheduleAssigneeDiagnostics,
  buildScheduleAuditorDiagnostics,
  buildAvailableScheduleAssignees,
  buildAvailableScheduleAuditors,
  findPendingAssigneeInvites,
  findPendingAuditorInvites,
  normalizeScheduleAssigneeIds,
  normalizeScheduleAuditorIds,
  resolveScheduleAssigneeLabels,
  resolveScheduleAuditorLabels,
  resolveScheduleAssigneeEmptyMessage,
} from "./scheduleAssignees";
