export const CURRENT_SCHEMA_VERSION = "3.0.0";

export const REQUIRED_TABS = [
  "Config",
  "Onboarding",
  "Users",
  "Schedule",
  "Actions",
  "ActionComments",
  "AuditResults",
  "AuditFindings",
  "Evidence",
  "Reports",
  "SyncLog",
  "Notes",
  "CompanyFolders",
] as const;

export type RequiredTab = (typeof REQUIRED_TABS)[number];

export const REQUIRED_COLUMNS: Record<RequiredTab, string[]> = {
  Config: ["Key", "Value", "Updated At"],
  Onboarding: [
    "Record ID",
    "Company ID",
    "Company Name",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  Users: [
    "User ID",
    "Company ID",
    "Email",
    "Name",
    "Role",
    "AccessLevel",
    "CompanyAreas",
    "Status",
    "Password" + "Hash",
    "PasswordUpdatedAt",
    "LastLoginAt",
    "InvitedAt",
    "CreatedAt",
    "UpdatedAt",
    "Full Name",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  Schedule: [
    "Root ID",
    "Schedule ID",
    "Version Number",
    "Version Label",
    "Lifecycle",
    "Company Folder ID",
    "Schedule Name",
    "Area ID",
    "Audit ID",
    "Audit Name",
    "Days",
    "Frequency",
    "Live Time",
    "Completion Hours",
    "Auditors",
    "Assigned Role",
    "Assigned User",
    "Status",
    "Created At",
    "Start Date",
    "End Date",
    "Updated At",
    "Parent Schedule ID",
    "Archived At",
    "Reactivated At",
    "Escalation User IDs",
    "Trigger Reaudit On Failure",
    "Reaudit Delay Hours",
    "Missed Audit Count",
    "Last Completed At",
    "Next Due At",
    "Health State",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  Actions: [
    "Action ID",
    "Company ID",
    "Source Audit ID",
    "Source Audit Name",
    "Source Question ID",
    "Source Question Text",
    "Source Answer",
    "Non Conformance ID",
    "Severity",
    "Status",
    "Assigned To User ID",
    "Assigned To Name",
    "Created By User ID",
    "Created At",
    "Updated At",
    "Due Date",
    "Closed At",
    "Verified By User ID",
    "Verification Notes",
    "Evidence Links",
    "Local Evidence Refs",
    "Comments",
    "Recurrence Flag",
    "Root Cause",
    "Corrective Action",
    "Preventive Action",
    "Risk Category",
    "Requires Manager Review",
    "Suggestion JSON",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
    "Version Number",
    "Local Updated At",
    "Remote Updated At",
    "Last Synced At",
  ],
  ActionComments: [
    "Comment ID",
    "Action ID",
    "Company ID",
    "Changed At",
    "Changed By",
    "From Status",
    "To Status",
    "Note",
    "Evidence Ref",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  AuditResults: [
    "Result ID",
    "Audit ID",
    "Area ID",
    "Company ID",
    "Audit Name",
    "Completed By",
    "Completed At",
    "Status",
    "Total Risk Score",
    "Highest Risk Level",
    "Critical Findings Count",
    "High Findings Count",
    "Answers JSON",
    "Signature Ref",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
    "Version Number",
    "Local Updated At",
    "Remote Updated At",
    "Last Synced At",
  ],
  AuditFindings: [
    "Finding ID",
    "Result ID",
    "Audit ID",
    "Area ID",
    "Company ID",
    "Question ID",
    "Question Text",
    "Answer",
    "Risk Level",
    "Risk Category",
    "Auto Action Required",
    "Requires Photo Evidence",
    "Requires Manager Review",
    "Note",
    "Local Evidence Refs",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  Evidence: [
    "Evidence ID",
    "Company ID",
    "Audit ID",
    "Action ID",
    "Finding ID",
    "File Name",
    "Mime Type",
    "Drive File ID",
    "Drive Link",
    "Local Ref",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  Reports: [
    "Report ID",
    "Company ID",
    "Report Type",
    "Title",
    "Created By",
    "Created At",
    "Visible To",
    "Export Links",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  SyncLog: [
    "Sync Item ID",
    "Company ID",
    "Entity Type",
    "Entity ID",
    "Operation",
    "Status",
    "Created At",
    "Attempted At",
    "Completed At",
    "Retry Count",
    "Priority",
    "Last Error",
    "Payload",
    "Schema Version",
  ],
  Notes: [
    "Note ID",
    "Company ID",
    "Context Type",
    "Context ID",
    "Note",
    "Created At",
    "Updated At",
    "Created By",
    "Updated By",
    "Sync Status",
    "Sync Attempts",
    "Last Sync Error",
    "Remote Row ID",
    "Schema Version",
  ],
  CompanyFolders: [
    "Folder Key",
    "Folder Name",
    "Folder ID",
    "Parent Folder ID",
    "Path",
    "Created At",
    "Last Checked At",
    "Status",
  ],
};

export const CONFIG_KEYS = [
  "schemaVersion",
  "companyId",
  "companyName",
  "createdAt",
  "lastValidatedAt",
  "lastRepairedAt",
  "appVersion",
  "defaultFormLanguage",
] as const;

export type ConfigKey = (typeof CONFIG_KEYS)[number];

export const SCHEMA_MIGRATIONS = [
  {
    version: "3.0.0",
    description: "Adds append-only audit history, evidence, sync log, and action comment support.",
  },
];

export function isRequiredTab(value: string): value is RequiredTab {
  return REQUIRED_TABS.includes(value as RequiredTab);
}
